config/routes.rb
Rails.application.routes.draw do
  
  

  #get 'museums/index'

  #get 'museums/show'

  #get 'museums/create'

  #get 'museums/new'

  #get 'museums/destroy'

  #get 'museums/edit'

  #get 'museums/update'

  #get 'author_categories/index'

  get 'author_categories/show'

  get 'author_categories/new'

  get 'author_categories/create'

  get 'author_categories/edit'

  get 'author_categories/update'

  get 'author_categories/destroy'

  resources :categories

  resources :museums
    
  resources :arts do
    resources :art_comments
  end
  
  resources :arts
  resources :author_categories

  resources :authors do
    resources :author_comments
  end

  devise_for :users
  resources :users
  root 'categories#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/art.rb
class Art < ActiveRecord::Base
	belongs_to :category
	has_many :art_comments
	#belongs_to :author
	belongs_to :user

	validates_presence_of :title, :style, :author
end

app/models/art_comment.rb
class ArtComment < ActiveRecord::Base
	belongs_to :art
	belongs_to :user

	validates_presence_of :title, :content
end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :arts
	has_many :author_comments
	belongs_to :user
  belongs_to :author_category

	validates_presence_of :name
end

app/models/author_category.rb
class AuthorCategory < ActiveRecord::Base
  has_many :authors

  validates_uniqueness_of :name
end

app/models/author_comment.rb
class AuthorComment < ActiveRecord::Base
	belongs_to :author
	belongs_to :user

	validates_presence_of :title, :content
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :arts

	validates_uniqueness_of :name
end

app/models/museum.rb
class Museum < ActiveRecord::Base
  has_many :arts

  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :art_comments
  has_many :author_comments
  has_many :authors
  has_many :arts

  validates_presence_of :email, :first_name, :last_name, :nick
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  expose(:category)
  expose(:art)
  expose(:arts) { Art.order(:rating) }
  expose(:art_comments, ancestor: :art)
  expose(:author)

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    self.art = Art.new(art_params)
    art.user_id = current_user.id
    if art.save
      arts << art
      redirect_to arts_path, notice: "Your work of art was successfully created"
    else 
      render :new
    end
  end

  def update
    if art.update(art_params)
      redirect_to category_art_url(category, art), notice: "Work of art was successfully updated"
    else 
      render :edit
    end
  end

  def destroy
    if art.destroy
      redirect_to category_url(art.category), notice: "Work of art was successfully deleted"
    end
  end

  private
  
  def art_params
    params.require(:art).permit(:title, :description, :production_date, :author, :style, :image, :owner, :location)
  end
end

app/controllers/author_categories_controller.rb
class AuthorCategoriesController < ApplicationController
  expose(:author_category)
  expose(:author_categories) { AuthorCategory.order(:name) }
  expose(:author) { Author.new }

  def index
  end

  def show
  end

  def new
  end

  def create
    author_category = AuthorCategory.new(author_category_params)
    if author_category.save
      redirect_to author_category, notice: 'Category was successfully created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if author_category.update(author_category_params)
      redirect_to author_category, notice: 'Category was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    author_category.destroy
    redirect_to author_categories_path, notice: 'Category was successfully deleted'
  end

  private

  def author_category_params
    params.require(:author_category).permit(:name)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  expose(:author_category)
  expose(:author)
  expose(:authors) {Author.order(:rating)}
  expose(:author_comments, ancestor: :author)

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    self.author = Author.new(author_params)
    author.user_id = current_user.id
    if author.save
      authors << author
      redirect_to authors_path, notice: "Author was successfully created"
    else
      render :new
    end
  end

  def update
    if author.update(author_params)
      redirect_to authors_path, notice: "Author was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    if author.destroy
      redirect_to authots_path
    end
  end

  private

  def author_params
    params.require(:author).permit(:name, :birth_date, :die_date, :hometown, :photo, :biography)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  expose(:category)
  expose(:categories) { Category.order(:name) }
  expose(:art) { Art.new }

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    category = Category.new(category_params)
    if category.save
      redirect_to category, notice: 'Category was successfully created'
    else
      render :new
    end
  end

  def update
    if category.update(category_params)
      redirect_to category, notice: 'Category was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    category.destroy
    redirect_to categories_path, notice: 'Category was successfully deleted'
  end

  private
  
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  expose(:museum)
  expose(:museums) { Museum.order(:name) }

  def index
  end

  def show
  end

  def create
    museum = Museum.new(museum_params)
    if museum.save
      redirect_to museum, notice: 'Museum was successfully created'
    else
      render :new
    end
  end

  def new
  end

  def destroy
    museum.destroy
    redirect_to museums_path, notice: 'Museum was successfully destroyed'
  end

  def edit
  end

  def update
    if museum.updated(museum_params)
      redirect_to museum, notice: 'Museum was successfully updated'
    else
      render :edit
    end
  end

  private

  def museum_params
    params.require(:museum).permit(:name, :address, :start_date, :location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose(:user)
  

  def show
  end

  def edit
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :nick, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/art_comments_helper.rb
module ArtCommentsHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/author_categories_helper.rb
module AuthorCategoriesHelper
end

app/helpers/author_comments_helper.rb
module AuthorCommentsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def is_admin?
    return current_user.try(:admin?)
  end
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/author_categories/_form.html.haml
= form_for author_category do |f|
  - if author_category.errors.any?
    #error_explanation
      %h2= "#{pluralize(category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - author_category.errors.full_message.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-success'

app/views/author_categories/create.html.haml
%h1 AuthorCategories#create
%p Find me in app/views/author_categories/create.html.haml

app/views/author_categories/destroy.html.haml
%h1 AuthorCategories#destroy
%p Find me in app/views/author_categories/destroy.html.haml

app/views/author_categories/edit.html.haml
%h1 Edit category

= render 'form'
%br
= link_to 'Show', author_category, class: 'btn btn-warning'
\|
= link_to 'Back', author_categories_path, class: "btn btn-primary"

app/views/author_categories/index.html.haml
%h1 Categories of authors
= link_to 'Add new category', new_author_category_path, class: 'btn btn-primary'

%table.table.table-striped
  %tr 
    %th Name
    %th
    %th
    %th
  - author_categories.each do |author_category|
    %tr
      %td= link_to author_category.name, author_category, class: 'btn btn-default'
      %td= link_to "Show", author_category, class: 'btn btn-warning'
      %td= link_to "Edit", edit_author_category_path(author_category), class: 'btn btn-info'
      %td= link_to "Delete", author_category, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger'

app/views/author_categories/new.html.haml
%h1 Add new category
= render 'form'

%br
= link_to 'Back', author_categories_path, class: 'btn btn-warning'

app/views/author_categories/show.html.haml
%h1 
  = author_category.name
-if user_signed_in?
  = render 'authors/form'
%br

-if author_category.authors.empty?
  "No authors in this category. Add new one!"
-else
  .panel.panel-default
    .panel.panel-primary
      Name:
    .panel-body
      = link_to author.name
  .panel.panel-default
    .panel.panel-primary
      Rating:
    .panel-body
      =author.rating
  .panel.panel-default
    .panel.panel-primary
      Birth date
    .panel-body
      =author.birth_date
  .panel.panel-default
    .panel.panel-primary
      Die date
    .panel-body
      =author.die_date
  .panel.panel-default
    .panel.panel-primary
      Hometown
    .panel-body
      =author.hometown
  .panel.panel-default
    .panel.panel-primary
      Photo
    .panel-body
      =author.photo
  .panel.panel-default
    .panel.panel-primary
      Biography
    .panel-body
      =author.biography

app/views/author_categories/update.html.haml
%h1 AuthorCategories#update
%p Find me in app/views/author_categories/update.html.haml